name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  ENV: ci

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24.11.0"
          cache: pnpm
      - name: Setup Rust
        run: rustup update stable
      - name: Setup cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run TypeScript Install
        run: pnpm install
      - name: Run TypeScript CI
        run: pnpm run ci
      - name: Run Rust CI
        run: pnpm run ci-rust
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
