name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: ./script/cibuild.ps1
        shell: pwsh
